name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    uses: cto-af/workflows/.github/workflows/node-ci.yml@main
    with:
      platforms: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      versions: '[22, 24, 25]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
